# Generated by Django 2.1.7 on 2019-03-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_binary', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_txt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wallet', models.IntegerField(default=None, max_length=42)),
                ('balance', models.FloatField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.User'),
        ),
    ]
