# Generated by Django 2.2.1 on 2019-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('file_hash', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('picture_name', models.CharField(default=None, max_length=20)),
                ('image', models.ImageField(default='/default_image.png', upload_to='')),
                ('price', models.IntegerField(default=None)),
                ('author', models.CharField(default=None, max_length=100)),
                ('wallet', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_txt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wallet', models.CharField(default=None, max_length=100)),
                ('balance', models.FloatField(default=None)),
            ],
        ),
    ]
