# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(default=None, max_length=20)),
                ('picture_binary', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='PictureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=5, max_length=10)),
                ('width', models.IntegerField(default=None)),
                ('height', models.IntegerField(default=None)),
                ('explanation', models.CharField(max_length=500)),
                ('picture_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capstone_db.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email_txt', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('wallet', models.IntegerField(default=None)),
                ('balance', models.FloatField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capstone_db.User'),
        ),
    ]
