# Generated by Django 2.2.1 on 2019-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture2',
            fields=[
                ('file_hash', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('picture_name', models.CharField(default=None, max_length=20)),
                ('image', models.ImageField(default='/default_image.png', upload_to='')),
                ('price', models.IntegerField(default=None)),
                ('author', models.CharField(default=None, max_length=100)),
                ('wallet', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
